name: CICD - Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Github Repository에서 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. docker 이미지를 빌드하고 tar 파일로 저장
    - name: Build Docker image
      run: |
        docker build -t mybible-api .
        docker save -o mybible-api.tar mybible-api

    #. 3. 비드한 도커 이미지 파일을 EC2로 전송 (SCP 사용)
    - name: Transfer Docker image to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ./mybible-api.tar
        target: /home/ec2-user/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # 4. EC2에서 도커 이미지 로드 및 컨테이너 실행
    - name: Deploy Docker container on EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 기존 컨테이너 종료 및 삭제
          docker stop mybible-api || true
          docker rm mybible-api || true

          # 도커 이미지 로드
          docker load -i /home/ec2-user/mybible-api.tar

          # 도커 컨테이너 실행
          docker run -d \
            --name mybible-api \
            -p 8080:8080 \
            mybible-api
    
        
